apiVersion: k3d.io/v1alpha3
kind: Simple
name: default
servers: 1
registries: # define how registries should be created or used
  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.localhost`
    name: default-registry
    host: "0.0.0.0"
    hostPort: "36167"