apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: patch.yaml
  target:
    group: apps
    kind: Deployment
    name: resistance-labs-base
    version: v1