apiVersion: apps/v1
kind: Deployment
metadata:
  name: resistance-labs-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: resistance-labs-base
  template:
    metadata:
      labels:
        app.kubernetes.io/name: resistance-labs-base
    spec:
      containers:
      - name: resistance-labs-base
        image: registry.digitalocean.com/web-images/resistance-labs-base:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 512Mi
