apiVersion: v1
kind: Service
metadata:
  labels:
    app: resistance-labs-base
  name: resistance-labs-base
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: resistance-labs-base