apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resistance-labs-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "resistancelabs.co"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: resistance-labs-base
            port:
              number: 5000