apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images: 
  - name: registry.digitalocean.com/web-images/resistance-labs-base
    newTag: v1.0.2
resources:
- ../base
- ingress.yaml
namespace: resistance-labs